name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRIC_TOKEN }}

          # Options
          user: DerTimonius
          filename: metrics.svg
          committer_message: "chore: update ${filename}"
          template: classic
          output_condition: skip-if-only-metadata-changed
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Vienna
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: jupyter notebook, html, css, mdx
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_notable: yes
          plugin_notable_filter: stars:>5000
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_skipped: autocomplete, refined-github, typescript-eslint
          plugin_notable_types: commit
